title: Avatar-Net: Multi-scale Zero-shot Style Transfer by Feature Decoration
description: Lu Sheng, Ziyi Lin, Jing Shao, Xiaogang Wang, IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2018
theme: jekyll-theme-cayman
